apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: dev

replicas:
- name: devops-hub
  count: 2

labels:
- pairs:
    environment: dev
  includeSelectors: false
  includeTemplates: true