apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "devops-hub.fullname" . }}
    labels:
       app: {{ .Values.labels.app }}
       environment: {{ .Values.labels.environment }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Values.labels.app }}
    template:
        metadata:
            labels:
                app: {{ .Values.labels.app }}
                environment: {{ .Values.labels.environment }}
        spec:
            containers:
            - name: {{  .Values.labels.app }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              ports:
              - containerPort: {{ .Values.service.port }}
              resources:
                requests:
                  memory: {{ .Values.resources.requests.memory }}
                  cpu: {{ .Values.resources.requests.cpu }}
                limits:
                  memory: {{ .Values.resources.limits.memory }}
                  cpu: {{ .Values.resources.limits.cpu }}